### ISSUE TITLE
"One or more order rows have a vat percent which is not valid for the provided country"

### ISSUE THREAD

**Issue by tlombert** [sveawebpay/opencart-module#8] opened 2018-04-21 22:37 UTC
Hi

I have got a problem with this; then choose invoice and delivery and have two tax (25% and 6%) I get this error "One or more order rows have a vat percent which is not valid for the provided country".

If I only change to pick-up it works. If I change the 6% tax to 25% it works. If I have direct payment with delivery and two tax it works.

I have checked my settings, and I have not change anything. All geo-code, tax-setting is OK.

Any suggestion?

EDIT: After some searching, I found that it is Svea Invoice Fee that is the error, if I change the tax inside Svea Invoice Fee to -- None -- or 0% it works.

We have in Sweden 6% tax for books, and the shipment is 25%, and it looks like the Svea Invoice Fee module don't handle two tax.

Best Regards
Thomas

**Comment by fre-sund** [comment] 2018-04-26 07:55
Hi,

Thanks for the report. The problem here is probably that the module tries to average the tax on the invoice fee for some reason even though it should be split up into two different rows. For example if you sell books for 50kr and the shipment is 50kr the invoice fee should be split up. 50% of the invoice fee should be with 25% tax and the other 50% of the invoice fee should be with 6% tax.

I will take a look at this and fix it as soon as I get time to.

Best regards,
Fredrik

**Comment by tlombert** [comment] 2018-05-24 19:38
Whats happening?
We still need an update on this?

**Comment by fre-sund** [comment] 2018-05-25 07:54
Sorry, I have a huge backlog which is why this isn't fixed yet. It will probably get fixed either today or next week.

**Comment by fre-sund** [comment] 2018-05-25 08:50
Which version of Opencart are you using?

**Comment by tlombert** [comment] 2018-05-25 10:20
We using 2.3.0.2
		
		

		Hämta Outlook för iOS
	




On Fri, May 25, 2018 at 10:55 AM +0200, "Fredrik Sundell" <notifications@github.com> wrote:












Which version of Opencart are you using?

**Comment by fre-sund** [comment] 2018-05-25 12:31
Can't seem to reproduce the problem. Here's my sort order and a finialized order:
![bild](https://user-images.githubusercontent.com/19384773/40544331-2bc76c1a-6028-11e8-9e70-762a91389d15.png)
![bild](https://user-images.githubusercontent.com/19384773/40544358-429e9c6a-6028-11e8-8a8e-a4b20cce1c59.png)


Do you have a step by step guide to reproducing the problem? Including a picture like the one above would be really helpful.

**Comment by tlombert** [comment] 2018-05-25 12:39
I fix that!
		
		

		Hämta Outlook för iOS
	




On Fri, May 25, 2018 at 2:36 PM +0200, "Fredrik Sundell" <notifications@github.com> wrote:












Can't seem to reproduce the problem. Here's my sort order and a finialized order:






Do you have a step by step guide to reproducing the problem? Including a picture like the one above would be really helpful.

**Comment by tlombert** [comment] 2018-05-25 19:46
Now I have activate tax again in the invoice fee-module, and now I don't get the error now then I try.
I have not done anything else, so there must be a thing with the setting. I will leave this on now and see if I get the error again.

In my test buy, all tax was correct now.

**Comment by fre-sund** [comment] 2018-05-28 10:53
Ok, since it works now I'll close the issue. If you encounter the same problem again, let me know.

**Comment by tlombert** [comment] 2018-05-28 20:00
Now I got it again.

It's then I only have a 6% tax product in the cart.

<img width="1156" alt="skarmavbild 2018-05-28 kl 21 50 08" src="https://user-images.githubusercontent.com/34110406/40627972-6885b6ba-62c2-11e8-82b1-b3dc0bc924f6.png">

If I have one 6% and a 25% tax product it works.

**Comment by fre-sund** [comment] 2018-05-29 07:27
I'll try and reproduce it.

**Comment by fre-sund** [comment] 2018-05-29 08:08
It works fine for me: 
![bild](https://user-images.githubusercontent.com/19384773/40645954-31b44514-6328-11e8-8eba-199e90237aa4.png)
![bild](https://user-images.githubusercontent.com/19384773/40645982-3c61cd56-6328-11e8-8163-f16bd983098b.png)

Can you send a picture of your configuration for taxes?

**Comment by tlombert** [comment] 2018-05-29 08:18
Here it comes.


[X]
Skärmavbild 2018-05-29 kl. 10.17.14.png
[X]
Skärmavbild 2018-05-29 kl. 10.17.04.png
[X]
Skärmavbild 2018-05-29 kl. 10.16.44.png
[X]
Skärmavbild 2018-05-29 kl. 10.16.30.png
[X]
Skärmavbild 2018-05-29 kl. 10.16.19.png
[X]
Skärmavbild 2018-05-29 kl. 10.15.47.png
[X]
Skärmavbild 2018-05-29 kl. 10.15.34.png
[cid:61645a99-47ac-43db-883a-6a6c47a890e3]??





________________________________
Från: Fredrik Sundell <notifications@github.com>
Skickat: den 29 maj 2018 10:08
Till: sveawebpay/opencart-module
Kopia: Thomas Lombert; Author
Ämne: Re: [sveawebpay/opencart-module] "One or more order rows have a vat percent which is not valid for the provided country" (#8)


It works fine for me:
[bild]<https://user-images.githubusercontent.com/19384773/40645954-31b44514-6328-11e8-8eba-199e90237aa4.png>
[bild]<https://user-images.githubusercontent.com/19384773/40645982-3c61cd56-6328-11e8-8163-f16bd983098b.png>

Can you send a picture of your configuration for taxes?

-

**Comment by fre-sund** [comment] 2018-05-29 08:20
I dont think it's possible to upload pictures via email to GitHub. They're just text for me.

**Comment by tlombert** [comment] 2018-05-29 08:21
Ok. :)

<img width="1287" alt="skarmavbild 2018-05-29 kl 10 17 14" src="https://user-images.githubusercontent.com/34110406/40646610-fedf33d6-6329-11e8-8f8c-9f495dd86561.png">
<img width="1279" alt="skarmavbild 2018-05-29 kl 10 17 04" src="https://user-images.githubusercontent.com/34110406/40646611-fef9d51a-6329-11e8-84dd-04adef8ec687.png">
<img width="1285" alt="skarmavbild 2018-05-29 kl 10 16 44" src="https://user-images.githubusercontent.com/34110406/40646612-ff175590-6329-11e8-8f2c-687423b440e9.png">
<img width="1271" alt="skarmavbild 2018-05-29 kl 10 16 30" src="https://user-images.githubusercontent.com/34110406/40646613-ff32d7fc-6329-11e8-99ca-349fe2b84e2a.png">
<img width="1271" alt="skarmavbild 2018-05-29 kl 10 16 19" src="https://user-images.githubusercontent.com/34110406/40646614-ff4d76c0-6329-11e8-8279-01b453885c11.png">
<img width="1287" alt="skarmavbild 2018-05-29 kl 10 15 47" src="https://user-images.githubusercontent.com/34110406/40646615-ff65ab28-6329-11e8-8de6-c6d7a25c1b01.png">
<img width="1276" alt="skarmavbild 2018-05-29 kl 10 15 34" src="https://user-images.githubusercontent.com/34110406/40646616-ff866bf6-6329-11e8-953e-9424c1b7c13d.png">
<img width="1282" alt="skarmavbild 2018-05-29 kl 10 15 15" src="https://user-images.githubusercontent.com/34110406/40646617-ffa7cb52-6329-11e8-830f-1d5460aae5a6.png">

**Comment by fre-sund** [comment] 2018-05-29 08:58
Thanks, and how is Svea Invoice Fee configured?

**Comment by tlombert** [comment] 2018-05-29 09:04
<img width="796" alt="skarmavbild 2018-05-29 kl 11 03 40" src="https://user-images.githubusercontent.com/34110406/40648964-07d1a8b0-6330-11e8-9777-bb31c780f82e.png">
And the rest of the countrys is disable

**Comment by fre-sund** [comment] 2018-05-29 09:06
It seems that your Svea Invoice Fee is configured improperly, there is a 74% VAT percent on the order. It's probably due to the sort order.

![bild](https://user-images.githubusercontent.com/19384773/40649073-46adc140-6330-11e8-977e-6dc74a4376c3.png)


The invoice fee should be before VAT. It could also be the tax class but I doubt it.

**Comment by tlombert** [comment] 2018-05-29 09:13
I'v got the same error even if Invoice fee is first.

<img width="1230" alt="skarmavbild 2018-05-29 kl 11 10 46" src="https://user-images.githubusercontent.com/34110406/40649447-3c4e9cfa-6331-11e8-9e10-f7475551db2d.png">

And there the 74 is coming from I don't knew..

**Comment by fre-sund** [comment] 2018-05-29 09:14
Now it's the shipping fee that's incorrect:
![bild](https://user-images.githubusercontent.com/19384773/40649519-6c5234de-6331-11e8-84e0-643f4b63bd03.png)

**Comment by fre-sund** [comment] 2018-05-29 09:16
Here are my sort orders, Svea Invoice Fee doesn't have a value but it seems to be fine anyways:
![bild](https://user-images.githubusercontent.com/19384773/40649616-abcdb548-6331-11e8-9c48-a30c68c87bce.png)

**Comment by tlombert** [comment] 2018-05-29 09:18
Have change to no sorting and the same error.

**Comment by fre-sund** [comment] 2018-05-29 09:19
It's not the invoice fee that's causing the problem after you changed the sort order it's the shipping, see my previous picture of the logs from your order.

**Comment by tlombert** [comment] 2018-05-29 09:42
Now I change the shipping tax to 0% and then it works. 

<img width="743" alt="skarmavbild 2018-05-29 kl 11 29 44" src="https://user-images.githubusercontent.com/34110406/40650497-b9c32ed8-6333-11e8-8439-298d9dd85a5b.png">

But now I cant get pass the shipping tab..
<img width="597" alt="skarmavbild 2018-05-29 kl 11 41 25" src="https://user-images.githubusercontent.com/34110406/40651150-4aa9eb20-6335-11e8-8121-dc420567051a.png">

**Comment by tlombert** [comment] 2018-05-29 09:50
What says the shipping vat now then it is 0%?

**Comment by fre-sund** [comment] 2018-05-29 11:39
If it's the order placed 11:43 the shipping vat is 13%

**Comment by tlombert** [comment] 2018-05-29 11:42
This make no sense? I have sent a mail to the developer of the delivery module, see what they say.
		
		

		Hämta Outlook för iOS
	




On Tue, May 29, 2018 at 1:39 PM +0200, "Fredrik Sundell" <notifications@github.com> wrote:












If it's the order placed 11:43 the shipping vat is 13%

**Comment by fre-sund** [comment] 2018-06-04 08:35
Closing this again, let me know if the issue remains after you've talked to them.

**Closed by fre-sund** 2018-06-04 08:35 UTC
