### ISSUE TITLE
Svea Directpayment wrong total

### ISSUE THREAD

**Issue by tlombert** [sveawebpay/opencart-module#10] opened 2019-01-01 21:36 UTC
Got I transfer from SEB <-> Svea Direct-payment.

Have a product that cost 33.89kr.

Without 25% tax = 27.11kr
Tax = 6.78kr
Use a round of module = +0.11kr
Customer should pay = 34.00kr

The amount that is taken from SEB = 33.78kr

Two questions;
Why is not the last total the amount pulled from bank?
How can it be -0.22kr, there is no sum like that.

<img width="420" alt="skarmavbild 2019-01-01 kl 22 17 23" src="https://user-images.githubusercontent.com/34110406/50576578-3357b980-0e15-11e9-9dad-7d9901672aaf.png">

<img width="1010" alt="skarmavbild 2019-01-01 kl 07 39 58" src="https://user-images.githubusercontent.com/34110406/50576588-51bdb500-0e15-11e9-8496-fc05fcfd7178.png">

<img width="386" alt="skarmavbild 2019-01-01 kl 22 34 54" src="https://user-images.githubusercontent.com/34110406/50576603-8598da80-0e15-11e9-9c99-dfb2b9dad732.png">

Best Regards
Thomas

**Comment by tlombert** [comment] 2019-01-07 07:37
Hi


Yes. We using this module;


https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=10016?


If you send me a real mail, I get send you the code so can yo see if there.


/Thomas


________________________________
Från: Fredrik Sundell <notifications@github.com>
Skickat: den 7 januari 2019 08:22
Till: sveawebpay/opencart-module
Kopia: Thomas Lombert; Author
Ämne: Re: [sveawebpay/opencart-module] Svea Directpayment wrong total (#10)


If I understand it correctly, you're using a module for rounding? Can you provide a link to it please?

-

**Comment by fre-sund** [comment] 2019-01-07 07:44
My email-adress is fredrik.sundell@sveaekonomi.se, shoot me a message :)

**Comment by fre-sund** [comment] 2019-01-11 10:13
The problem seems to be caused in the payment module and is not specific to any payment method, be it directbank or SCO. The problem occurs in some code that is shared between all payment methods and has to do with how the module adds the tax to the order rows which are sent to Svea.

To fix this issue the code for handling order rows needs to be rewritten, which is not a small fix since it will require some rigorous testing to make sure that everything works as intended.

I would advice deactivating the module until this is done, otherwise the price will be incorrect. I will probably be able to get a fix out next week or so.

**Comment by fre-sund** [comment] 2019-01-16 07:33
I have commited a fix now, there will be a release later this week that will solve the issue. I'll inform you once the commit is pushed to GitHub.

**Comment by tlombert** [comment] 2019-01-16 21:08
?Perfect!


I'll wait..



________________________________
Från: Fredrik Sundell <notifications@github.com>
Skickat: den 16 januari 2019 08:33
Till: sveawebpay/opencart-module
Kopia: Thomas Lombert; Author
Ämne: Re: [sveawebpay/opencart-module] Svea Directpayment wrong total (#10)


I have commited a fix now, there will be a release later this week that will solve the issue. I'll inform you once the commit is pushed to GitHub.

-

**Comment by fre-sund** [comment] 2019-01-18 13:36
The release has been delayed until monday, I'm afraid. I will inform you once it's available.

**Comment by fre-sund** [comment] 2019-01-21 16:02
@tlombert Here's the release: https://github.com/sveawebpay/opencart-module/releases/tag/v4.5.0

**Closed by fre-sund** 2019-01-21 16:02 UTC
